name: "Prepare Earthly"
description: "Prepare Earthly"

inputs:
  dockerhub_username:
    description: Dockerhub Username
    default: drselump14
  dockerhub_token:
    description: Dockerhub token
    required: true

runs:
  using: "composite"
  steps:
    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: drselump14
        password: ${{github.token}}

    - name: Install earthly
      uses: earthly/actions-setup@v1
      with:
        version: 0.7.1

    - name: Log in to the DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ inputs.dockerhub_username }}
        password: ${{ inputs.dockerhub_token }}
